#!/usr/bin/python

import sys
import os

path_filename=os.path.abspath(__file__)
executablesDir = os.path.split(path_filename)[0]
sys.path.insert(0,os.path.join(executablesDir,"python"))

# user defined classes
from Project import *
from ProjectManager import *

#project = Project()
#
#project.setSolidFile("g6_schwert.stl")
#project.setObjeScaling("0.001")
#project.prepare()
#project.create()
#print(project)
#project.createGrid()

manager = ProjectManager()
manager.prepare()
manager.createProjects()
manager.selectProjectToRun()
